name: Case Manager Server Update

on: pull_request

concurrency:
  group: self-aws-hosted-${{ github.head_ref || github.ref }}-${{ github.base_ref }}
  cancel-in-progress: true

# env:
#   GOPATH: /root/cm/appdata/godata
#   GOCACHE: /root/cm/appdata/godata/cache
#   HOME: /root/

jobs:
  build:
    name: Building the case manager app
    runs-on: NewCaseManagerRunnerLabel
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      #      - name: Workaround the missing path environments
      #        run: |
      #          echo -n "/root/.nvm/versions/node/v14.20.0/bin:" >> $GITHUB_PATH
      #          echo -n "/usr/local/go/bin" >> $GITHUB_PATH

      - name: Check out the repository code
        uses: actions/checkout@v2

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      #      - name: Set the app configuration on the right location
      #        run: cp /root/cm/appdata/app.ini ./custom/conf/

      - run: echo "🖥️ The workflow is now ready to start building the ${{ github.repository }} code."

      - name: Build the app
        run: TAGS="bindata" make build
