name: Case Manager Server Update

on: pull_request

concurrency:
  group: self-aws-hosted-${{ github.head_ref || github.ref }}-${{ github.base_ref }}
  cancel-in-progress: true

env:
  GOCACHE: /home/ubuntu/cmtools/appdata/godata/cache
  GOPATH: /home/ubuntu/cmtools/appdata/godata
#   HOME: /root/

jobs:
  build:
    name: Building the case manager app
    runs-on: NewCaseManagerRunnerLabel
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Workaround the missing path environments
        run: |
          echo -n "/usr/local/go/bin" >> $GITHUB_PATH

      - name: Check out the repository code
        uses: actions/checkout@v2

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      #      - name: Set the app configuration on the right location
      #        run: cp /root/cm/appdata/app.ini ./custom/conf/

      - run: echo "🖥️ The workflow is now ready to start building the ${{ github.repository }} code."
      - run: systemctl list-unit-files --no-pager |grep newfile

      - name: Build the app
        id: NewBuild
        run: TAGS="bindata" make build

      - name: Move it to the git folder
        if: contains( steps.NewBuild.outcome , 'success' )
        run: |
          systemctl stop filemanager.service
          systemctl status filemanager.service
          cp ./gitea /home/git/newfilemanager/filemanager
          systemctl start filemanager.service
          systemctl status filemanager.service

        # chown git:git /home/git/newfilemanager/filemanager
